### ISSUE TITLE
Can't figure out how to use imagesloaded

### ISSUE THREAD

**Issue by xzilja** [metafizzy/flickity-imagesloaded#2]
I npm installed flickity and am including it into my project via es6 syntac in the following way:

`import Flickity from 'flickity';`

and calling it with following options

```
this.flkty = new Flickity(this.refs.carousel, {
      cellAlign: 'left',
      wrapAround: false,
      pageDots: false,
      prevNextButtons: false,
      draggable: true,
      freeScroll: false,
      autoPlay: false,
      imagesLoaded: true
    });
```

but imagesLoaded doesn't seem to work in my case, as container still cuts them off.

**Comment by oskarrough** [comment]
You are importing `flickity` and not `flickity-imagesloaded`, which is what you're looking for.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Flickity. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).
