### ISSUE TITLE
Could you please update it to the newest version?

### ISSUE THREAD

**Issue by sedlukha** [metafizzy/flickity-imagesloaded#4]
Excuse me for this issue, but I really need this update

**Comment by desandro** [comment]
There is nothing to update. flickity-imagesloaded is v2.0.0, which is included in [flickity.pkgd.js](https://github.com/metafizzy/flickity/blob/v2.0.5/dist/flickity.pkgd.js#L4578). imagesLoaded is v4.1.1, which is [included in `flickity.pkgd.js`](https://github.com/metafizzy/flickity/blob/v2.0.5/dist/flickity.pkgd.js#L4207)

Is there something I'm missing?

**Comment by sedlukha** [comment]
I'm talking about the latest flickity version. 2.0.5

**Comment by desandro** [comment]
Where is Flickity not updated to v2.0.5?
